import pygame
import time

# Inicialização do Pygame
pygame.init()

# Definição das cores
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)

# Configurações da janela do jogo
window_width = 800
window_height = 600
game_display = pygame.display.set_mode((window_width, window_height))
pygame.display.set_caption('Jogo da Cobrinha')

# Variáveis de controle do jogo
clock = pygame.time.Clock()
snake_block_size = 10
snake_speed = 30

font_style = pygame.font.SysFont(None, 30)

def message(msg, color):
    mesg = font_style.render(msg, True, color)
    game_display.blit(mesg, [window_width / 6, window_height / 3])

def game_loop():
    game_over = False
    game_close = False

    # Posição inicial da cobrinha
    x1 = window_width / 2
    y1 = window_height / 2

    # Movimento inicial
    x1_change = 0
    y1_change = 0

    while not game_over:

        while game_close:
            game_display.fill(WHITE)
            message("Você perdeu! Pressione Q para sair ou C para jogar novamente", RED)
            pygame.display.update()

            for event in pygame.event.get():
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_q:
                        game_over = True
                        game_close = False
                    if event.key == pygame.K_c:
                        game_loop()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                game_over = True
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_LEFT:
                    x1_change = -snake_block_size
                    y1_change = 0
                elif event.key == pygame.K_RIGHT:
                    x1_change = snake_block_size
                    y1_change = 0
                elif event.key == pygame.K_UP:
                    y1_change = -snake_block_size
                    x1_change = 0
                elif event.key == pygame.K_DOWN:
                    y1_change = snake_block_size
                    x1_change = 0

        # Verifica se a cobrinha saiu da tela
        if x1 >= window_width or x1 < 0 or y1 >= window_height or y1 < 0:
            game_close = True

        x1 += x1_change
        y1 += y1_change
        game_display.fill(WHITE)
        pygame.draw.rect(game_display, BLACK, [x1, y1, snake_block_size, snake_block_size])
        pygame.display.update()

        clock.tick(snake_speed)

    pygame.quit()


game_loop()

