nome : Jobs para atualizar dados
    run-on : ubuntu-latest
    passos :
      # cartões de resumo
      - usa : ações/checkout@v2
      - usa : vn7n24fzkq/github-profile-summary-cards@release
        ambiente :
          GITHUB_TOKEN : ${{ segredos.GITHUB_TOKEN }}
        com :
          NOME DE USUÁRIO : ${{ github.repository_owner }}

      # Animação de Cobra
      - usa : Platane/snk@master
        id : cobra-gif
